added read time , views and claps
arEdHQ/arEd-blogs pull request #5
Opened 2021-04-17 10:19 UTC by shivalee12

2021-04-17 20:46 UTC, harsh-not-haarsh requested changes
Complete all 7 changes, also, make smaller PRs!

2021-04-17 20:46 UTC, harsh-not-haarsh commented on blogs/models.py
> +        # help_text='This image will be displayed as\
why is this commented?

2021-04-17 20:46 UTC, harsh-not-haarsh commented on blogs/models.py
> +    # def __str__(self):
why is this commented?

2021-04-17 20:46 UTC, harsh-not-haarsh commented on blogs/views.py
> +# from django.http import HttpResponseRedirect
remove this rather than commenting it

2021-04-17 20:46 UTC, harsh-not-haarsh commented on blogs/views.py
>  class BlogLikeToggle(RedirectView):
are you using ```BlogLikeToggle``` or ```BlogLikeAPIToggle``` or both?

2021-04-17 20:46 UTC, harsh-not-haarsh commented on templates/details.html
> +<strong class="text-secondary"> {{ blog.number_of_likes }} Clap{{ blog.number_of_likes|pluralize }}</strong>
Have consistent nomenclature, either keep likes or keep claps

2021-04-17 20:46 UTC, harsh-not-haarsh commented on .gitignore
> +.env.example
you should actually change this to ```.env.*```. gitignore can have regex matches. read what regex is and what * means.

2021-04-17 20:46 UTC, harsh-not-haarsh commented on .gitignore
> +.env.example
Also, keep better names for the files. ```.example``` doesn't tell me what the file contains. Keep better names.

2021-04-18 03:30 UTC, shivalee12 commented on blogs/views.py
>  class BlogLikeToggle(RedirectView):
we are using both

2021-04-18 14:29 UTC, harsh-not-haarsh approved these changes

2021-04-18 14:29 UTC, merged